export interface AskAiAssistantPayload {
  question: string;
  threadId?: string;
}

export type AiAssistantGraphType = "line" | "bar" | "pie" | "doughnut";

export type AiAssistantGraphValueFormat = "currency" | "number";

export interface AiAssistantGraphDataset {
  label: string;
  data: number[];
  /**
   * Optional because the current AI Assistant SSE graph payload does not
   * include presentation colors. The chart renderer supplies a stable
   * frontend palette when it is absent.
   */
  color?: string;
}

export interface AiAssistantGraph {
  type: AiAssistantGraphType;
  title: string;
  xAxisLabel: string;
  yAxisLabel: string;
  valueFormat: AiAssistantGraphValueFormat;
  labels: string[];
  datasets: AiAssistantGraphDataset[];
}

/**
 * A backend-stored assistant artifact. Reports are generated by the backend;
 * the frontend only uses the signed URL to open the completed document.
 */
export interface AiAssistantAttachment {
  id: string;
  fileName: string;
  mimeType: string;
  signedUrl: string;
}

export type AiAssistantPdfStatus = "generating" | "ready";

export interface AiAssistantPdfEventData {
  status: AiAssistantPdfStatus;
  /** Present while the backend is preparing the report when it supplies one. */
  title?: string;
  /** Present once a backend-generated report is ready to open. */
  attachment?: AiAssistantAttachment;
}

/**
 * A verified customer result returned by the AI customer tool. `profit` is
 * intentionally optional because the backend only includes it when the
 * assistant specifically asks for customer profit.
 */
export interface AiAssistantCustomerInsight {
  id: string;
  name: string;
  phone: string;
  address: string;
  saleCount: number;
  salesTotal: number;
  paidSales: number;
  salesBalance: number;
  purchaseCount: number;
  purchaseTotal: number;
  paidPurchases: number;
  purchaseBalance: number;
  profit?: number;
  createdAt: string;
}

export interface AiAssistantCustomerInsightsData {
  customers: AiAssistantCustomerInsight[];
  totalCount?: number;
}

export type AiAssistantToolStatus = "started" | "completed" | "failed";

export interface AiAssistantToolEventData {
  toolCallId: string;
  toolName: string;
  status: AiAssistantToolStatus;
  /** Human-readable progress/failure information when the backend supplies it. */
  message?: string;
  /**
   * Present when a customer tool result is included in the event. Keeping
   * customer data normalized here lets the UI support a single lookup, search
   * results, and customer lists through the same callback.
   */
  customerInsights?: AiAssistantCustomerInsightsData;
}

export interface AiAssistantToolCallEventData
  extends AiAssistantToolEventData {
  status: "started";
}

export interface AiAssistantToolResultEventData
  extends AiAssistantToolEventData {
  status: "completed" | "failed";
}

export interface AiAssistantChunkEventData {
  content: string;
}

export interface AiAssistantGraphEventData {
  graph: AiAssistantGraph;
}

export interface AiAssistantDoneEventData {
  content: string;
  threadId: string;
  userMessageId: string;
  assistantMessageId: string;
  /** Backend-generated report files associated with this assistant response. */
  attachments?: AiAssistantAttachment[];
  /** Optional customer data included alongside a final assistant response. */
  customerInsights?: AiAssistantCustomerInsightsData;
}

export interface AiAssistantErrorEventData {
  threadId: string;
  userMessageId: string;
  message: string;
}

export type AiAssistantSseEvent =
  | { event: "tool"; data: AiAssistantToolEventData }
  | { event: "tool-call"; data: AiAssistantToolCallEventData }
  | { event: "tool-result"; data: AiAssistantToolResultEventData }
  | { event: "chunk"; data: AiAssistantChunkEventData }
  | { event: "graph"; data: AiAssistantGraphEventData }
  | { event: "pdf"; data: AiAssistantPdfEventData }
  | { event: "done"; data: AiAssistantDoneEventData }
  | { event: "error"; data: AiAssistantErrorEventData };

export interface RenameAiChatThreadPayload {
  name: string;
}

export interface DeleteAiChatThreadResponse {
  message: string;
  id: string;
}

export type AiChatRole = "user" | "assistant";

export interface AiChatThreadSummary {
  id: string;
  title?: string;
  lastMessageAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface AiChatMessage {
  id: string;
  role: AiChatRole;
  content: string;
  status?: "completed" | "failed";
  errorMessage?: string | null;
  model?: string | null;
  provider?: string | null;
  /** Saved backend-generated artifacts for this message. */
  attachments?: AiAssistantAttachment[];
  metadata?: Record<string, unknown> | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface AiChatThreadDetail extends AiChatThreadSummary {
  messages: AiChatMessage[];
}
